### ISSUE TITLE
Problems with add_trackDefinition

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/reindeer#23]
Linda and I did some testing and we are running into two different errors with the add_trackDefinition function, specifying gender or not and the number of files you upload seems to matter, but I'm not sure I can see a consistent pattern in it.

Here's 2 examples:

This error was with 4 uploaded wav files in a single session with default metadata (gender unspecified & age 35):

`Error in `*tmp*`[[jj]] : subscript out of bounds\nCalls: add_trackDefinition ... get_metadata -> export_metadata -> [<- -> [<-.data.frame\nExecution halted`

When trying it again with the same 4 wav files but this time with gender set to Male:
`Error: Not all sounds files were assigned metadata 4 ==> 0\nExecution halted`

And this is what the function calls look like:
`add_trackDefinition(VISPDB, name = "FORMANTS", onTheFlyFunctionName = "forest")`
`add_trackDefinition(VISPDB, name = "F0", onTheFlyFunctionName = "ksvF0")`

Both of these cases also results in ssffTrackDefinitions being empty in VISP_DBconfig.json

BUT - sometimes it does work. Generally it seems to work better when a session contains fewer wavs.

**Comment by FredrikKarlssonSpeech** [comment]
Odd. Is it possible to pack the project up to a zip file and attach it?

**Comment by johanvonboer** [comment]
Well, since it just so happens that we have an online collaboration platform for exactly this type of projects I decided to invite you there instead - will be a good test too! :)

Don't know if you will receive some sort of invitation email so here's the links to the repos in case not:

https://gitlab.visp.humlab.umu.se/jonlig04_at_umu_dot_se/test-4-spec-clean

https://gitlab.visp.humlab.umu.se/jonlig04_at_umu_dot_se/test-4-unspec-clean

test-4-spec-clean was with gender specified, which worked

test-4-unspec-clean was with gender unspecified which failed 

The "clean" in the names just refer to me using cleaned up filenames, I was wondering earlier if that could be the issue.

**Comment by FredrikKarlssonSpeech** [comment]
Added more tests, and the fix seems to work. Please import to VISP

**Comment by johanvonboer** [comment]
I have updated the session containers now
